#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x03996C7C83F12F11 (srl295@keybase.io)
#
Name     : compat-icu4c-soname63
Version  : 63.1
Release  : 22
URL      : http://download.icu-project.org/files/icu4c/63.1/icu4c-63_1-src.tgz
Source0  : http://download.icu-project.org/files/icu4c/63.1/icu4c-63_1-src.tgz
Source99 : http://download.icu-project.org/files/icu4c/63.1/icu4c-63_1-src.tgz.asc
Summary  : International Components for Unicode
Group    : Development/Tools
License  : NCSA
Requires: compat-icu4c-soname63-bin = %{version}-%{release}
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Requires: compat-icu4c-soname63-lib = %{version}-%{release}
Requires: compat-icu4c-soname63-license = %{version}-%{release}
Requires: compat-icu4c-soname63-man = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : sed

%description
ICU is a set of C and C++ libraries that provides robust and full-featured
Unicode and locale support. The library provides calendar support, conversions
for many character sets, language sensitive collation, date
and time formatting, support for many locales, message catalogs
and resources, message formatting, normalization, number and currency
formatting, time zones support, transliteration, word, line and
sentence breaking, etc.

This package contains the Unicode character database and derived
properties, along with converters and time zones data.

This package contains the runtime libraries for ICU. It does
not contain any of the data files needed at runtime and present in the
`icu' and `icu-locales` packages.

%package bin
Summary: bin components for the compat-icu4c-soname63 package.
Group: Binaries
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Requires: compat-icu4c-soname63-license = %{version}-%{release}

%description bin
bin components for the compat-icu4c-soname63 package.


%package data
Summary: data components for the compat-icu4c-soname63 package.
Group: Data

%description data
data components for the compat-icu4c-soname63 package.


%package dev
Summary: dev components for the compat-icu4c-soname63 package.
Group: Development
Requires: compat-icu4c-soname63-lib = %{version}-%{release}
Requires: compat-icu4c-soname63-bin = %{version}-%{release}
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Provides: compat-icu4c-soname63-devel = %{version}-%{release}
Requires: compat-icu4c-soname63 = %{version}-%{release}
Requires: compat-icu4c-soname63 = %{version}-%{release}

%description dev
dev components for the compat-icu4c-soname63 package.


%package dev32
Summary: dev32 components for the compat-icu4c-soname63 package.
Group: Default
Requires: compat-icu4c-soname63-lib32 = %{version}-%{release}
Requires: compat-icu4c-soname63-bin = %{version}-%{release}
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Requires: compat-icu4c-soname63-dev = %{version}-%{release}

%description dev32
dev32 components for the compat-icu4c-soname63 package.


%package lib
Summary: lib components for the compat-icu4c-soname63 package.
Group: Libraries
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Requires: compat-icu4c-soname63-license = %{version}-%{release}

%description lib
lib components for the compat-icu4c-soname63 package.


%package lib32
Summary: lib32 components for the compat-icu4c-soname63 package.
Group: Default
Requires: compat-icu4c-soname63-data = %{version}-%{release}
Requires: compat-icu4c-soname63-license = %{version}-%{release}

%description lib32
lib32 components for the compat-icu4c-soname63 package.


%package license
Summary: license components for the compat-icu4c-soname63 package.
Group: Default

%description license
license components for the compat-icu4c-soname63 package.


%package man
Summary: man components for the compat-icu4c-soname63 package.
Group: Default

%description man
man components for the compat-icu4c-soname63 package.


%prep
%setup -q -n icu
pushd ..
cp -a icu build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559758899
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
pushd source
%configure --disable-static
make  %{?_smp_mflags}
popd

pushd ../build32/source
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1559758899
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-icu4c-soname63
cp license.html %{buildroot}/usr/share/package-licenses/compat-icu4c-soname63/license.html
pushd ../build32/source
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd source
%make_install
popd

%files
%defattr(-,root,root,-)
%exclude /usr/lib32/icu/Makefile.inc
%exclude /usr/lib32/icu/current
%exclude /usr/lib32/icu/pkgdata.inc
%exclude /usr/lib64/icu/Makefile.inc
%exclude /usr/lib64/icu/current
%exclude /usr/lib64/icu/pkgdata.inc
/usr/lib32/icu/63.1/Makefile.inc
/usr/lib32/icu/63.1/pkgdata.inc
/usr/lib64/icu/63.1/Makefile.inc
/usr/lib64/icu/63.1/pkgdata.inc

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/derb
%exclude /usr/bin/escapesrc
%exclude /usr/bin/genbrk
%exclude /usr/bin/genccode
%exclude /usr/bin/gencfu
%exclude /usr/bin/gencmn
%exclude /usr/bin/gencnval
%exclude /usr/bin/gendict
%exclude /usr/bin/gennorm2
%exclude /usr/bin/genrb
%exclude /usr/bin/gensprep
%exclude /usr/bin/icu-config
%exclude /usr/bin/icuinfo
%exclude /usr/bin/icupkg
%exclude /usr/bin/makeconv
%exclude /usr/bin/pkgdata
%exclude /usr/bin/uconv

%files data
%defattr(-,root,root,-)
%exclude /usr/share/icu/63.1/LICENSE
%exclude /usr/share/icu/63.1/config/mh-linux
%exclude /usr/share/icu/63.1/install-sh
%exclude /usr/share/icu/63.1/mkinstalldirs

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/unicode/alphaindex.h
%exclude /usr/include/unicode/appendable.h
%exclude /usr/include/unicode/basictz.h
%exclude /usr/include/unicode/brkiter.h
%exclude /usr/include/unicode/bytestream.h
%exclude /usr/include/unicode/bytestrie.h
%exclude /usr/include/unicode/bytestriebuilder.h
%exclude /usr/include/unicode/calendar.h
%exclude /usr/include/unicode/caniter.h
%exclude /usr/include/unicode/casemap.h
%exclude /usr/include/unicode/char16ptr.h
%exclude /usr/include/unicode/chariter.h
%exclude /usr/include/unicode/choicfmt.h
%exclude /usr/include/unicode/coleitr.h
%exclude /usr/include/unicode/coll.h
%exclude /usr/include/unicode/compactdecimalformat.h
%exclude /usr/include/unicode/curramt.h
%exclude /usr/include/unicode/currpinf.h
%exclude /usr/include/unicode/currunit.h
%exclude /usr/include/unicode/datefmt.h
%exclude /usr/include/unicode/dbbi.h
%exclude /usr/include/unicode/dcfmtsym.h
%exclude /usr/include/unicode/decimfmt.h
%exclude /usr/include/unicode/docmain.h
%exclude /usr/include/unicode/dtfmtsym.h
%exclude /usr/include/unicode/dtintrv.h
%exclude /usr/include/unicode/dtitvfmt.h
%exclude /usr/include/unicode/dtitvinf.h
%exclude /usr/include/unicode/dtptngen.h
%exclude /usr/include/unicode/dtrule.h
%exclude /usr/include/unicode/edits.h
%exclude /usr/include/unicode/enumset.h
%exclude /usr/include/unicode/errorcode.h
%exclude /usr/include/unicode/fieldpos.h
%exclude /usr/include/unicode/filteredbrk.h
%exclude /usr/include/unicode/fmtable.h
%exclude /usr/include/unicode/format.h
%exclude /usr/include/unicode/fpositer.h
%exclude /usr/include/unicode/gender.h
%exclude /usr/include/unicode/gregocal.h
%exclude /usr/include/unicode/icudataver.h
%exclude /usr/include/unicode/icuplug.h
%exclude /usr/include/unicode/idna.h
%exclude /usr/include/unicode/listformatter.h
%exclude /usr/include/unicode/localpointer.h
%exclude /usr/include/unicode/locdspnm.h
%exclude /usr/include/unicode/locid.h
%exclude /usr/include/unicode/measfmt.h
%exclude /usr/include/unicode/measunit.h
%exclude /usr/include/unicode/measure.h
%exclude /usr/include/unicode/messagepattern.h
%exclude /usr/include/unicode/msgfmt.h
%exclude /usr/include/unicode/normalizer2.h
%exclude /usr/include/unicode/normlzr.h
%exclude /usr/include/unicode/nounit.h
%exclude /usr/include/unicode/numberformatter.h
%exclude /usr/include/unicode/numberrangeformatter.h
%exclude /usr/include/unicode/numfmt.h
%exclude /usr/include/unicode/numsys.h
%exclude /usr/include/unicode/parseerr.h
%exclude /usr/include/unicode/parsepos.h
%exclude /usr/include/unicode/platform.h
%exclude /usr/include/unicode/plurfmt.h
%exclude /usr/include/unicode/plurrule.h
%exclude /usr/include/unicode/ptypes.h
%exclude /usr/include/unicode/putil.h
%exclude /usr/include/unicode/rbbi.h
%exclude /usr/include/unicode/rbnf.h
%exclude /usr/include/unicode/rbtz.h
%exclude /usr/include/unicode/regex.h
%exclude /usr/include/unicode/region.h
%exclude /usr/include/unicode/reldatefmt.h
%exclude /usr/include/unicode/rep.h
%exclude /usr/include/unicode/resbund.h
%exclude /usr/include/unicode/schriter.h
%exclude /usr/include/unicode/scientificnumberformatter.h
%exclude /usr/include/unicode/search.h
%exclude /usr/include/unicode/selfmt.h
%exclude /usr/include/unicode/simpleformatter.h
%exclude /usr/include/unicode/simpletz.h
%exclude /usr/include/unicode/smpdtfmt.h
%exclude /usr/include/unicode/sortkey.h
%exclude /usr/include/unicode/std_string.h
%exclude /usr/include/unicode/strenum.h
%exclude /usr/include/unicode/stringoptions.h
%exclude /usr/include/unicode/stringpiece.h
%exclude /usr/include/unicode/stringtriebuilder.h
%exclude /usr/include/unicode/stsearch.h
%exclude /usr/include/unicode/symtable.h
%exclude /usr/include/unicode/tblcoll.h
%exclude /usr/include/unicode/timezone.h
%exclude /usr/include/unicode/tmunit.h
%exclude /usr/include/unicode/tmutamt.h
%exclude /usr/include/unicode/tmutfmt.h
%exclude /usr/include/unicode/translit.h
%exclude /usr/include/unicode/tzfmt.h
%exclude /usr/include/unicode/tznames.h
%exclude /usr/include/unicode/tzrule.h
%exclude /usr/include/unicode/tztrans.h
%exclude /usr/include/unicode/ubidi.h
%exclude /usr/include/unicode/ubiditransform.h
%exclude /usr/include/unicode/ubrk.h
%exclude /usr/include/unicode/ucal.h
%exclude /usr/include/unicode/ucasemap.h
%exclude /usr/include/unicode/ucat.h
%exclude /usr/include/unicode/uchar.h
%exclude /usr/include/unicode/ucharstrie.h
%exclude /usr/include/unicode/ucharstriebuilder.h
%exclude /usr/include/unicode/uchriter.h
%exclude /usr/include/unicode/uclean.h
%exclude /usr/include/unicode/ucnv.h
%exclude /usr/include/unicode/ucnv_cb.h
%exclude /usr/include/unicode/ucnv_err.h
%exclude /usr/include/unicode/ucnvsel.h
%exclude /usr/include/unicode/ucol.h
%exclude /usr/include/unicode/ucoleitr.h
%exclude /usr/include/unicode/uconfig.h
%exclude /usr/include/unicode/ucpmap.h
%exclude /usr/include/unicode/ucptrie.h
%exclude /usr/include/unicode/ucsdet.h
%exclude /usr/include/unicode/ucurr.h
%exclude /usr/include/unicode/udat.h
%exclude /usr/include/unicode/udata.h
%exclude /usr/include/unicode/udateintervalformat.h
%exclude /usr/include/unicode/udatpg.h
%exclude /usr/include/unicode/udisplaycontext.h
%exclude /usr/include/unicode/uenum.h
%exclude /usr/include/unicode/ufieldpositer.h
%exclude /usr/include/unicode/uformattable.h
%exclude /usr/include/unicode/ugender.h
%exclude /usr/include/unicode/uidna.h
%exclude /usr/include/unicode/uiter.h
%exclude /usr/include/unicode/uldnames.h
%exclude /usr/include/unicode/ulistformatter.h
%exclude /usr/include/unicode/uloc.h
%exclude /usr/include/unicode/ulocdata.h
%exclude /usr/include/unicode/umachine.h
%exclude /usr/include/unicode/umisc.h
%exclude /usr/include/unicode/umsg.h
%exclude /usr/include/unicode/umutablecptrie.h
%exclude /usr/include/unicode/unifilt.h
%exclude /usr/include/unicode/unifunct.h
%exclude /usr/include/unicode/unimatch.h
%exclude /usr/include/unicode/unirepl.h
%exclude /usr/include/unicode/uniset.h
%exclude /usr/include/unicode/unistr.h
%exclude /usr/include/unicode/unorm.h
%exclude /usr/include/unicode/unorm2.h
%exclude /usr/include/unicode/unum.h
%exclude /usr/include/unicode/unumberformatter.h
%exclude /usr/include/unicode/unumsys.h
%exclude /usr/include/unicode/uobject.h
%exclude /usr/include/unicode/upluralrules.h
%exclude /usr/include/unicode/uregex.h
%exclude /usr/include/unicode/uregion.h
%exclude /usr/include/unicode/ureldatefmt.h
%exclude /usr/include/unicode/urename.h
%exclude /usr/include/unicode/urep.h
%exclude /usr/include/unicode/ures.h
%exclude /usr/include/unicode/uscript.h
%exclude /usr/include/unicode/usearch.h
%exclude /usr/include/unicode/uset.h
%exclude /usr/include/unicode/usetiter.h
%exclude /usr/include/unicode/ushape.h
%exclude /usr/include/unicode/uspoof.h
%exclude /usr/include/unicode/usprep.h
%exclude /usr/include/unicode/ustdio.h
%exclude /usr/include/unicode/ustream.h
%exclude /usr/include/unicode/ustring.h
%exclude /usr/include/unicode/ustringtrie.h
%exclude /usr/include/unicode/utext.h
%exclude /usr/include/unicode/utf.h
%exclude /usr/include/unicode/utf16.h
%exclude /usr/include/unicode/utf32.h
%exclude /usr/include/unicode/utf8.h
%exclude /usr/include/unicode/utf_old.h
%exclude /usr/include/unicode/utmscale.h
%exclude /usr/include/unicode/utrace.h
%exclude /usr/include/unicode/utrans.h
%exclude /usr/include/unicode/utypes.h
%exclude /usr/include/unicode/uvernum.h
%exclude /usr/include/unicode/uversion.h
%exclude /usr/include/unicode/vtzone.h
%exclude /usr/lib64/libicudata.so
%exclude /usr/lib64/libicui18n.so
%exclude /usr/lib64/libicuio.so
%exclude /usr/lib64/libicutest.so
%exclude /usr/lib64/libicutu.so
%exclude /usr/lib64/libicuuc.so
%exclude /usr/lib64/pkgconfig/icu-i18n.pc
%exclude /usr/lib64/pkgconfig/icu-io.pc
%exclude /usr/lib64/pkgconfig/icu-uc.pc

%files dev32
%defattr(-,root,root,-)
%exclude /usr/lib32/libicudata.so
%exclude /usr/lib32/libicui18n.so
%exclude /usr/lib32/libicuio.so
%exclude /usr/lib32/libicutest.so
%exclude /usr/lib32/libicutu.so
%exclude /usr/lib32/libicuuc.so
%exclude /usr/lib32/pkgconfig/32icu-i18n.pc
%exclude /usr/lib32/pkgconfig/32icu-io.pc
%exclude /usr/lib32/pkgconfig/32icu-uc.pc
%exclude /usr/lib32/pkgconfig/icu-i18n.pc
%exclude /usr/lib32/pkgconfig/icu-io.pc
%exclude /usr/lib32/pkgconfig/icu-uc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libicudata.so.63
/usr/lib64/libicudata.so.63.1
/usr/lib64/libicui18n.so.63
/usr/lib64/libicui18n.so.63.1
/usr/lib64/libicuio.so.63
/usr/lib64/libicuio.so.63.1
/usr/lib64/libicutest.so.63
/usr/lib64/libicutest.so.63.1
/usr/lib64/libicutu.so.63
/usr/lib64/libicutu.so.63.1
/usr/lib64/libicuuc.so.63
/usr/lib64/libicuuc.so.63.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libicudata.so.63
/usr/lib32/libicudata.so.63.1
/usr/lib32/libicui18n.so.63
/usr/lib32/libicui18n.so.63.1
/usr/lib32/libicuio.so.63
/usr/lib32/libicuio.so.63.1
/usr/lib32/libicutest.so.63
/usr/lib32/libicutest.so.63.1
/usr/lib32/libicutu.so.63
/usr/lib32/libicutu.so.63.1
/usr/lib32/libicuuc.so.63
/usr/lib32/libicuuc.so.63.1

%files license
%defattr(0644,root,root,0755)
%exclude /usr/share/package-licenses/compat-icu4c-soname63/license.html

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man1/derb.1
%exclude /usr/share/man/man1/genbrk.1
%exclude /usr/share/man/man1/gencfu.1
%exclude /usr/share/man/man1/gencnval.1
%exclude /usr/share/man/man1/gendict.1
%exclude /usr/share/man/man1/genrb.1
%exclude /usr/share/man/man1/icu-config.1
%exclude /usr/share/man/man1/makeconv.1
%exclude /usr/share/man/man1/pkgdata.1
%exclude /usr/share/man/man1/uconv.1
%exclude /usr/share/man/man8/genccode.8
%exclude /usr/share/man/man8/gencmn.8
%exclude /usr/share/man/man8/gensprep.8
%exclude /usr/share/man/man8/icupkg.8
