#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xACA5DBE1FD8FABF1 (srl@icu-project.org)
#
Name     : compat-icu4c-soname63
Version  : 63.2
Release  : 29
URL      : https://github.com/unicode-org/icu/releases/download/release-63-2/icu4c-63_2-src.tgz
Source0  : https://github.com/unicode-org/icu/releases/download/release-63-2/icu4c-63_2-src.tgz
Source1 : https://github.com/unicode-org/icu/releases/download/release-63-2/icu4c-63_2-src.tgz.asc
Summary  : International Components for Unicode
Group    : Development/Tools
License  : NCSA
Requires: compat-icu4c-soname63-lib = %{version}-%{release}
Requires: compat-icu4c-soname63-license = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : sed
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
ICU is a set of C and C++ libraries that provides robust and full-featured
Unicode and locale support. The library provides calendar support, conversions
for many character sets, language sensitive collation, date
and time formatting, support for many locales, message catalogs
and resources, message formatting, normalization, number and currency
formatting, time zones support, transliteration, word, line and
sentence breaking, etc.

This package contains the Unicode character database and derived
properties, along with converters and time zones data.

This package contains the runtime libraries for ICU. It does
not contain any of the data files needed at runtime and present in the
`icu' and `icu-locales` packages.

%package lib
Summary: lib components for the compat-icu4c-soname63 package.
Group: Libraries
Requires: compat-icu4c-soname63-license = %{version}-%{release}

%description lib
lib components for the compat-icu4c-soname63 package.


%package lib32
Summary: lib32 components for the compat-icu4c-soname63 package.
Group: Default
Requires: compat-icu4c-soname63-license = %{version}-%{release}

%description lib32
lib32 components for the compat-icu4c-soname63 package.


%package license
Summary: license components for the compat-icu4c-soname63 package.
Group: Default

%description license
license components for the compat-icu4c-soname63 package.


%prep
%setup -q -n icu
pushd ..
cp -a icu build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568234909
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
pushd source
%configure --disable-static
make  %{?_smp_mflags}
popd

pushd ../build32/source
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1568234909
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-icu4c-soname63
cp license.html %{buildroot}/usr/share/package-licenses/compat-icu4c-soname63/license.html
pushd ../build32/source
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd source
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/lib32/icu/63.1/Makefile.inc
rm -f %{buildroot}/usr/lib32/icu/63.1/pkgdata.inc
rm -f %{buildroot}/usr/lib32/icu/Makefile.inc
rm -f %{buildroot}/usr/lib32/icu/current
rm -f %{buildroot}/usr/lib32/icu/pkgdata.inc
rm -f %{buildroot}/usr/lib64/icu/63.1/Makefile.inc
rm -f %{buildroot}/usr/lib64/icu/63.1/pkgdata.inc
rm -f %{buildroot}/usr/lib64/icu/Makefile.inc
rm -f %{buildroot}/usr/lib64/icu/current
rm -f %{buildroot}/usr/lib64/icu/pkgdata.inc
rm -f %{buildroot}/usr/include/unicode/alphaindex.h
rm -f %{buildroot}/usr/include/unicode/appendable.h
rm -f %{buildroot}/usr/include/unicode/basictz.h
rm -f %{buildroot}/usr/include/unicode/brkiter.h
rm -f %{buildroot}/usr/include/unicode/bytestream.h
rm -f %{buildroot}/usr/include/unicode/bytestrie.h
rm -f %{buildroot}/usr/include/unicode/bytestriebuilder.h
rm -f %{buildroot}/usr/include/unicode/calendar.h
rm -f %{buildroot}/usr/include/unicode/caniter.h
rm -f %{buildroot}/usr/include/unicode/casemap.h
rm -f %{buildroot}/usr/include/unicode/char16ptr.h
rm -f %{buildroot}/usr/include/unicode/chariter.h
rm -f %{buildroot}/usr/include/unicode/choicfmt.h
rm -f %{buildroot}/usr/include/unicode/coleitr.h
rm -f %{buildroot}/usr/include/unicode/coll.h
rm -f %{buildroot}/usr/include/unicode/compactdecimalformat.h
rm -f %{buildroot}/usr/include/unicode/curramt.h
rm -f %{buildroot}/usr/include/unicode/currpinf.h
rm -f %{buildroot}/usr/include/unicode/currunit.h
rm -f %{buildroot}/usr/include/unicode/datefmt.h
rm -f %{buildroot}/usr/include/unicode/dbbi.h
rm -f %{buildroot}/usr/include/unicode/dcfmtsym.h
rm -f %{buildroot}/usr/include/unicode/decimfmt.h
rm -f %{buildroot}/usr/include/unicode/docmain.h
rm -f %{buildroot}/usr/include/unicode/dtfmtsym.h
rm -f %{buildroot}/usr/include/unicode/dtintrv.h
rm -f %{buildroot}/usr/include/unicode/dtitvfmt.h
rm -f %{buildroot}/usr/include/unicode/dtitvinf.h
rm -f %{buildroot}/usr/include/unicode/dtptngen.h
rm -f %{buildroot}/usr/include/unicode/dtrule.h
rm -f %{buildroot}/usr/include/unicode/edits.h
rm -f %{buildroot}/usr/include/unicode/enumset.h
rm -f %{buildroot}/usr/include/unicode/errorcode.h
rm -f %{buildroot}/usr/include/unicode/fieldpos.h
rm -f %{buildroot}/usr/include/unicode/filteredbrk.h
rm -f %{buildroot}/usr/include/unicode/fmtable.h
rm -f %{buildroot}/usr/include/unicode/format.h
rm -f %{buildroot}/usr/include/unicode/fpositer.h
rm -f %{buildroot}/usr/include/unicode/gender.h
rm -f %{buildroot}/usr/include/unicode/gregocal.h
rm -f %{buildroot}/usr/include/unicode/icudataver.h
rm -f %{buildroot}/usr/include/unicode/icuplug.h
rm -f %{buildroot}/usr/include/unicode/idna.h
rm -f %{buildroot}/usr/include/unicode/listformatter.h
rm -f %{buildroot}/usr/include/unicode/localpointer.h
rm -f %{buildroot}/usr/include/unicode/locdspnm.h
rm -f %{buildroot}/usr/include/unicode/locid.h
rm -f %{buildroot}/usr/include/unicode/measfmt.h
rm -f %{buildroot}/usr/include/unicode/measunit.h
rm -f %{buildroot}/usr/include/unicode/measure.h
rm -f %{buildroot}/usr/include/unicode/messagepattern.h
rm -f %{buildroot}/usr/include/unicode/msgfmt.h
rm -f %{buildroot}/usr/include/unicode/normalizer2.h
rm -f %{buildroot}/usr/include/unicode/normlzr.h
rm -f %{buildroot}/usr/include/unicode/nounit.h
rm -f %{buildroot}/usr/include/unicode/numberformatter.h
rm -f %{buildroot}/usr/include/unicode/numberrangeformatter.h
rm -f %{buildroot}/usr/include/unicode/numfmt.h
rm -f %{buildroot}/usr/include/unicode/numsys.h
rm -f %{buildroot}/usr/include/unicode/parseerr.h
rm -f %{buildroot}/usr/include/unicode/parsepos.h
rm -f %{buildroot}/usr/include/unicode/platform.h
rm -f %{buildroot}/usr/include/unicode/plurfmt.h
rm -f %{buildroot}/usr/include/unicode/plurrule.h
rm -f %{buildroot}/usr/include/unicode/ptypes.h
rm -f %{buildroot}/usr/include/unicode/putil.h
rm -f %{buildroot}/usr/include/unicode/rbbi.h
rm -f %{buildroot}/usr/include/unicode/rbnf.h
rm -f %{buildroot}/usr/include/unicode/rbtz.h
rm -f %{buildroot}/usr/include/unicode/regex.h
rm -f %{buildroot}/usr/include/unicode/region.h
rm -f %{buildroot}/usr/include/unicode/reldatefmt.h
rm -f %{buildroot}/usr/include/unicode/rep.h
rm -f %{buildroot}/usr/include/unicode/resbund.h
rm -f %{buildroot}/usr/include/unicode/schriter.h
rm -f %{buildroot}/usr/include/unicode/scientificnumberformatter.h
rm -f %{buildroot}/usr/include/unicode/search.h
rm -f %{buildroot}/usr/include/unicode/selfmt.h
rm -f %{buildroot}/usr/include/unicode/simpleformatter.h
rm -f %{buildroot}/usr/include/unicode/simpletz.h
rm -f %{buildroot}/usr/include/unicode/smpdtfmt.h
rm -f %{buildroot}/usr/include/unicode/sortkey.h
rm -f %{buildroot}/usr/include/unicode/std_string.h
rm -f %{buildroot}/usr/include/unicode/strenum.h
rm -f %{buildroot}/usr/include/unicode/stringoptions.h
rm -f %{buildroot}/usr/include/unicode/stringpiece.h
rm -f %{buildroot}/usr/include/unicode/stringtriebuilder.h
rm -f %{buildroot}/usr/include/unicode/stsearch.h
rm -f %{buildroot}/usr/include/unicode/symtable.h
rm -f %{buildroot}/usr/include/unicode/tblcoll.h
rm -f %{buildroot}/usr/include/unicode/timezone.h
rm -f %{buildroot}/usr/include/unicode/tmunit.h
rm -f %{buildroot}/usr/include/unicode/tmutamt.h
rm -f %{buildroot}/usr/include/unicode/tmutfmt.h
rm -f %{buildroot}/usr/include/unicode/translit.h
rm -f %{buildroot}/usr/include/unicode/tzfmt.h
rm -f %{buildroot}/usr/include/unicode/tznames.h
rm -f %{buildroot}/usr/include/unicode/tzrule.h
rm -f %{buildroot}/usr/include/unicode/tztrans.h
rm -f %{buildroot}/usr/include/unicode/ubidi.h
rm -f %{buildroot}/usr/include/unicode/ubiditransform.h
rm -f %{buildroot}/usr/include/unicode/ubrk.h
rm -f %{buildroot}/usr/include/unicode/ucal.h
rm -f %{buildroot}/usr/include/unicode/ucasemap.h
rm -f %{buildroot}/usr/include/unicode/ucat.h
rm -f %{buildroot}/usr/include/unicode/uchar.h
rm -f %{buildroot}/usr/include/unicode/ucharstrie.h
rm -f %{buildroot}/usr/include/unicode/ucharstriebuilder.h
rm -f %{buildroot}/usr/include/unicode/uchriter.h
rm -f %{buildroot}/usr/include/unicode/uclean.h
rm -f %{buildroot}/usr/include/unicode/ucnv.h
rm -f %{buildroot}/usr/include/unicode/ucnv_cb.h
rm -f %{buildroot}/usr/include/unicode/ucnv_err.h
rm -f %{buildroot}/usr/include/unicode/ucnvsel.h
rm -f %{buildroot}/usr/include/unicode/ucol.h
rm -f %{buildroot}/usr/include/unicode/ucoleitr.h
rm -f %{buildroot}/usr/include/unicode/uconfig.h
rm -f %{buildroot}/usr/include/unicode/ucpmap.h
rm -f %{buildroot}/usr/include/unicode/ucptrie.h
rm -f %{buildroot}/usr/include/unicode/ucsdet.h
rm -f %{buildroot}/usr/include/unicode/ucurr.h
rm -f %{buildroot}/usr/include/unicode/udat.h
rm -f %{buildroot}/usr/include/unicode/udata.h
rm -f %{buildroot}/usr/include/unicode/udateintervalformat.h
rm -f %{buildroot}/usr/include/unicode/udatpg.h
rm -f %{buildroot}/usr/include/unicode/udisplaycontext.h
rm -f %{buildroot}/usr/include/unicode/uenum.h
rm -f %{buildroot}/usr/include/unicode/ufieldpositer.h
rm -f %{buildroot}/usr/include/unicode/uformattable.h
rm -f %{buildroot}/usr/include/unicode/ugender.h
rm -f %{buildroot}/usr/include/unicode/uidna.h
rm -f %{buildroot}/usr/include/unicode/uiter.h
rm -f %{buildroot}/usr/include/unicode/uldnames.h
rm -f %{buildroot}/usr/include/unicode/ulistformatter.h
rm -f %{buildroot}/usr/include/unicode/uloc.h
rm -f %{buildroot}/usr/include/unicode/ulocdata.h
rm -f %{buildroot}/usr/include/unicode/umachine.h
rm -f %{buildroot}/usr/include/unicode/umisc.h
rm -f %{buildroot}/usr/include/unicode/umsg.h
rm -f %{buildroot}/usr/include/unicode/umutablecptrie.h
rm -f %{buildroot}/usr/include/unicode/unifilt.h
rm -f %{buildroot}/usr/include/unicode/unifunct.h
rm -f %{buildroot}/usr/include/unicode/unimatch.h
rm -f %{buildroot}/usr/include/unicode/unirepl.h
rm -f %{buildroot}/usr/include/unicode/uniset.h
rm -f %{buildroot}/usr/include/unicode/unistr.h
rm -f %{buildroot}/usr/include/unicode/unorm.h
rm -f %{buildroot}/usr/include/unicode/unorm2.h
rm -f %{buildroot}/usr/include/unicode/unum.h
rm -f %{buildroot}/usr/include/unicode/unumberformatter.h
rm -f %{buildroot}/usr/include/unicode/unumsys.h
rm -f %{buildroot}/usr/include/unicode/uobject.h
rm -f %{buildroot}/usr/include/unicode/upluralrules.h
rm -f %{buildroot}/usr/include/unicode/uregex.h
rm -f %{buildroot}/usr/include/unicode/uregion.h
rm -f %{buildroot}/usr/include/unicode/ureldatefmt.h
rm -f %{buildroot}/usr/include/unicode/urename.h
rm -f %{buildroot}/usr/include/unicode/urep.h
rm -f %{buildroot}/usr/include/unicode/ures.h
rm -f %{buildroot}/usr/include/unicode/uscript.h
rm -f %{buildroot}/usr/include/unicode/usearch.h
rm -f %{buildroot}/usr/include/unicode/uset.h
rm -f %{buildroot}/usr/include/unicode/usetiter.h
rm -f %{buildroot}/usr/include/unicode/ushape.h
rm -f %{buildroot}/usr/include/unicode/uspoof.h
rm -f %{buildroot}/usr/include/unicode/usprep.h
rm -f %{buildroot}/usr/include/unicode/ustdio.h
rm -f %{buildroot}/usr/include/unicode/ustream.h
rm -f %{buildroot}/usr/include/unicode/ustring.h
rm -f %{buildroot}/usr/include/unicode/ustringtrie.h
rm -f %{buildroot}/usr/include/unicode/utext.h
rm -f %{buildroot}/usr/include/unicode/utf.h
rm -f %{buildroot}/usr/include/unicode/utf16.h
rm -f %{buildroot}/usr/include/unicode/utf32.h
rm -f %{buildroot}/usr/include/unicode/utf8.h
rm -f %{buildroot}/usr/include/unicode/utf_old.h
rm -f %{buildroot}/usr/include/unicode/utmscale.h
rm -f %{buildroot}/usr/include/unicode/utrace.h
rm -f %{buildroot}/usr/include/unicode/utrans.h
rm -f %{buildroot}/usr/include/unicode/utypes.h
rm -f %{buildroot}/usr/include/unicode/uvernum.h
rm -f %{buildroot}/usr/include/unicode/uversion.h
rm -f %{buildroot}/usr/include/unicode/vtzone.h
rm -f %{buildroot}/usr/lib32/icu/63.2/Makefile.inc
rm -f %{buildroot}/usr/lib32/icu/63.2/pkgdata.inc
rm -f %{buildroot}/usr/lib32/libicudata.so
rm -f %{buildroot}/usr/lib32/libicui18n.so
rm -f %{buildroot}/usr/lib32/libicuio.so
rm -f %{buildroot}/usr/lib32/libicutest.so
rm -f %{buildroot}/usr/lib32/libicutu.so
rm -f %{buildroot}/usr/lib32/libicuuc.so
rm -f %{buildroot}/usr/lib32/pkgconfig/32icu-i18n.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32icu-io.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/32icu-uc.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/icu-i18n.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/icu-io.pc
rm -f %{buildroot}/usr/lib32/pkgconfig/icu-uc.pc
rm -f %{buildroot}/usr/lib64/icu/63.2/Makefile.inc
rm -f %{buildroot}/usr/lib64/icu/63.2/pkgdata.inc
rm -f %{buildroot}/usr/lib64/libicudata.so
rm -f %{buildroot}/usr/lib64/libicui18n.so
rm -f %{buildroot}/usr/lib64/libicuio.so
rm -f %{buildroot}/usr/lib64/libicutest.so
rm -f %{buildroot}/usr/lib64/libicutu.so
rm -f %{buildroot}/usr/lib64/libicuuc.so
rm -f %{buildroot}/usr/lib64/pkgconfig/icu-i18n.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/icu-io.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/icu-uc.pc
rm -f %{buildroot}/usr/share/icu/63.2/LICENSE
rm -f %{buildroot}/usr/share/icu/63.2/config/mh-linux
rm -f %{buildroot}/usr/share/icu/63.2/install-sh
rm -f %{buildroot}/usr/share/icu/63.2/mkinstalldirs
rm -f %{buildroot}/usr/share/man/man1/derb.1
rm -f %{buildroot}/usr/share/man/man1/genbrk.1
rm -f %{buildroot}/usr/share/man/man1/gencfu.1
rm -f %{buildroot}/usr/share/man/man1/gencnval.1
rm -f %{buildroot}/usr/share/man/man1/gendict.1
rm -f %{buildroot}/usr/share/man/man1/genrb.1
rm -f %{buildroot}/usr/share/man/man1/icu-config.1
rm -f %{buildroot}/usr/share/man/man1/makeconv.1
rm -f %{buildroot}/usr/share/man/man1/pkgdata.1
rm -f %{buildroot}/usr/share/man/man1/uconv.1
rm -f %{buildroot}/usr/share/man/man8/genccode.8
rm -f %{buildroot}/usr/share/man/man8/gencmn.8
rm -f %{buildroot}/usr/share/man/man8/gensprep.8
rm -f %{buildroot}/usr/share/man/man8/icupkg.8
## install_append content
rm -rf %{buildroot}/usr/bin
## install_append end

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libicudata.so.63
/usr/lib64/libicudata.so.63.2
/usr/lib64/libicui18n.so.63
/usr/lib64/libicui18n.so.63.2
/usr/lib64/libicuio.so.63
/usr/lib64/libicuio.so.63.2
/usr/lib64/libicutest.so.63
/usr/lib64/libicutest.so.63.2
/usr/lib64/libicutu.so.63
/usr/lib64/libicutu.so.63.2
/usr/lib64/libicuuc.so.63
/usr/lib64/libicuuc.so.63.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libicudata.so.63
/usr/lib32/libicudata.so.63.2
/usr/lib32/libicui18n.so.63
/usr/lib32/libicui18n.so.63.2
/usr/lib32/libicuio.so.63
/usr/lib32/libicuio.so.63.2
/usr/lib32/libicutest.so.63
/usr/lib32/libicutest.so.63.2
/usr/lib32/libicutu.so.63
/usr/lib32/libicutu.so.63.2
/usr/lib32/libicuuc.so.63
/usr/lib32/libicuuc.so.63.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-icu4c-soname63/license.html
